### ISSUE TITLE
Add I001 to ignore in ruff template config

### ISSUE THREAD

**Issue by pa-decarvalho** [pa-decarvalho/python-template#42]
```toml
[lint]
select = ["ALL"]
ignore = ["D203", "D212", "RUF012", "ANN401", "I001"]
```
